# Generated by Django 4.1.7 on 2026-08-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_tasacambio'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cuenta_por_cobrar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='cuentas.cuentaporcobrar'),
        ),
    ]
