# Generated by Django 4.1.7 on 2026-08-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cuenta_por_cobrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('divisa', 'Divisa'), ('otro', 'Otro')], max_length=20),
        ),
    ]
