# Generated by Django 4.1.7 on 2026-09-04 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_categoria_producto_nombre_unico_por_negocio_and_more'),
        ('ventas', '0004_venta_numero_venta_venta_numero_unico_por_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='productos.presentacionproducto'),
        ),
    ]
