# Generated by Django 4.1.7 on 2026-09-12 00:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_detalleventa_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='factor_presentacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle_pago',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_descuento',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('fijo', 'Monto fijo')], max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='valor_descuento',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
