# Generated by Django 4.1.7 on 2026-08-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación'),
        ),
    ]
