# Generated by Django 4.1.7 on 2026-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_alter_cuentaporcobrar_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fecha_vigencia', models.DateField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente', models.CharField(default='BCV', max_length=100)),
            ],
            options={
                'ordering': ['-fecha_vigencia', '-id'],
            },
        ),
    ]
