# Generated by Django 4.1.7 on 2026-08-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_tasacambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='pendiente', max_length=10),
        ),
    ]
