# Generated by Django 4.1.7 on 2026-08-08 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("admin", "Administrador"), ("empleado", "Empleado")],
                        default="empleado",
                        max_length=10,
                    ),
                ),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="miembros",
                        to="usuarios.negocio",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_negocio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuloNegocio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("clientes", "Clientes"),
                            ("cuentas", "Cuentas por cobrar"),
                            ("inventario", "Inventario"),
                            ("compras", "Compras"),
                            ("ventas", "Ventas"),
                            ("caja", "Caja"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "negocio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulos",
                        to="usuarios.negocio",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="modulonegocio",
            constraint=models.UniqueConstraint(
                fields=("negocio", "modulo"), name="modulo_unico_por_negocio"
            ),
        ),
    ]
