# Generated by Django 4.1.7 on 2026-08-07 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_finalizar_inventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="color",
            field=models.CharField(
                default="#0d6efd",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Introduce un color hexadecimal válido (por ejemplo, #0d6efd).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
    ]
