# Generated by Django 4.1.7 on 2026-08-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_categoria_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto físico'), ('servicio', 'Servicio')], default='producto', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('hoja', 'Hoja'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('metro', 'Metro')], default='unidad', max_length=20),
        ),
    ]
