# Generated by Django 4.1.7 on 2026-08-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_producto_stock_alter_producto_stock_minimo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='producto_nombre_unico_por_negocio'),
        ),
    ]
