# Generated by Django 4.1.7 on 2026-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_categoria_producto_nombre_unico_por_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
