# Generated by Django 4.1.7 on 2026-09-03 17:15

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_unidades', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='productos.producto')),
            ],
            options={
                'ordering': ['cantidad_unidades', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='presentacionproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'nombre'), name='presentacion_nombre_unico_por_producto'),
        ),
    ]
