# Generated by Django 4.1.7 on 2026-09-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_presentacionproducto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='categoria',
            name='producto_nombre_unico_por_negocio',
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('negocio', 'nombre'), name='producto_nombre_unico_por_negocio'),
        ),
    ]
