# Generated by Django 4.1.7 on 2026-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_remove_categoria_producto_nombre_unico_por_negocio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_base',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('litro', 'Litro'), ('ml', 'Mililitro'), ('metro', 'Metro')], default='unidad', max_length=20),
        ),
    ]
