# Generated by Django 4.1.7 on 2026-08-05 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_dia_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dia_pago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='mensualidad',
        ),
    ]
