# Generated by Django 4.1.7 on 2026-08-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clientes', '0003_remove_cliente_dia_pago_remove_cliente_mensualidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.negocio'),
        ),
    ]
