# Generated by Django 4.1.7 on 2026-08-05 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('clientes', '0004_cliente_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='usuarios.negocio'),
        ),
    ]
