# Generated by Django 4.1.7 on 2026-08-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('divisa', 'Divisa'), ('otro', 'Otro')], default='efectivo', max_length=20),
        ),
    ]
